// MARK: Edit Contact 
let numberSection = 1
let emailSection = 2
let urlSection = 5
let addressSection = 6
let birthdaySection = 7
let dateSection = 8
let relatedNameSection = 9
let socialProfileSection = 10
let messageSection = 11
// MARK: Info Contact
let numSection = 0
